TRUNCATE unit_types RESTART IDENTITY;

TRUNCATE actions RESTART IDENTITY;

TRUNCATE phases RESTART IDENTITY;

TRUNCATE seasons RESTART IDENTITY;

TRUNCATE users RESTART IDENTITY;

TRUNCATE games RESTART IDENTITY;

TRUNCATE countries RESTART IDENTITY;

TRUNCATE maps RESTART IDENTITY;

TRUNCATE locations RESTART IDENTITY CASCADE;

TRUNCATE borders RESTART IDENTITY CASCADE;

TRUNCATE coasts RESTART IDENTITY CASCADE;

TRUNCATE coast_borders RESTART IDENTITY CASCADE;

TRUNCATE service_providers RESTART IDENTITY CASCADE;

TRUNCATE user_chat_services RESTART IDENTITY CASCADE;

TRUNCATE players RESTART IDENTITY CASCADE;

TRUNCATE turns RESTART IDENTITY CASCADE;

TRUNCATE map_locations RESTART IDENTITY CASCADE;

TRUNCATE units RESTART IDENTITY CASCADE;

TRUNCATE orders RESTART IDENTITY CASCADE;

INSERT INTO
    unit_types (unit_type)
VALUES ('ARMY'), ('NAVY');

INSERT INTO
    actions ("action")
VALUES ('HOLD'), ('MOVE'), ('SUPPORT'), ('CONVOY');

INSERT INTO
    phases (phase)
VALUES ('MOVEMENT'), ('RETREAT'), ('DISBAND'), ('BUILD');

INSERT INTO
    seasons (season)
VALUES ('SPRING'), ('SUMMER'), ('FALL'), ('WINTER');

INSERT INTO
    countries ("name", abbreviation, adjective)
VALUES ('Austria', 'AUS', 'Austrian'), ('England', 'ENG', 'English'), ('France', 'FRA', 'French'), ('Germany', 'GER', 'German'), ('Italy', 'ITA', 'Italian'), ('Russia', 'RUS', 'Russian'), ('Turkey', 'TUR', 'Turkish');